name: Chris Walker Innerwealth
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82952
title: Making the Most Out of Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9eacf'
    - '#060c08'
    - '#b18878'
    - '#7e7831'
    - '#4a5314'
  brandStrength: 0.5
  lightness: 0.5075817515607923
  saturation: 0.5
  rhythmicContrast: 0.3565314926672727
purpose: []
