name: Chris Walker Innerwealth
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82952
title: Making the Most Out of Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bf292e'
    - '#fefefe'
    - '#bebebe'
    - '#f5713f'
    - '#040204'
  brandStrength: 0
  lightness: 0.5075817515607923
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
